### ISSUE TITLE
Issues with Rst_Hydrolase-Tm__Hydrolase-Tm.hmm

### ISSUE THREAD

**Issue by chrisdoering8197** [mdmparis/defense-finder-models#17]
I've recently install defense finder and I'm running into errors when I first try to run it. I run into the following error: 

macsypy.error.MacsypyError: 'defense-finder-models/Rst_Hydrolase-Tm__Hydrolase-Tm': No such profile

I have tried downloading defense finder via pip install in a few different fresh conda environments on both a Linux and Mac and receive the same error each time. On the Mac install I tried deleting the Hydrolase system from the profile, rules, and definitions and instead received the following error:

macsypy.error.MacsypyError: 'defense-finder-models/Rst_RT-Tm__RT-Tm': No such profile

I've included the full traceback below. Any help would be appreciated, thank you.

```
Traceback (most recent call last):
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/profile.py", line 70, in get_profile
    path = model_location.get_profile(gene.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/registries.py", line 344, in get_profile
    return self._profiles[name]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'Rst_Hydrolase-Tm__Hydrolase-Tm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/bin/defense-finder", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/defense_finder_cli/main.py", line 143, in run
    defense_finder.run(protein_file_name, dbtype, workers, coverage, tmp_dir, models_dir, no_cut_ga, loglevel)
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/defense_finder/__init__.py", line 29, in run
    macsyfinder.main(args=msf_cmd)
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/scripts/macsyfinder.py", line 1193, in main
    all_systems, rejected_candidates = search_systems(config, model_registry, models_def_to_detect, logger)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/scripts/macsyfinder.py", line 529, in search_systems
    parser.parse(models_def_to_detect)
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/definition_parser.py", line 85, in parse
    self._fill_gene_bank(model_node, model_location, def_loc)
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/definition_parser.py", line 287, in _fill_gene_bank
    self.gene_bank.add_new_gene(model_location, gene_name, self.profile_factory)
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/gene.py", line 102, in add_new_gene
    gene = CoreGene(model_location, name, profile_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/gene.py", line 114, in __init__
    self._profile = profile_factory.get_profile(self, model_location)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gridsan/cdoering/.conda/envs/DefenseFinder/lib/python3.12/site-packages/macsypy/profile.py", line 72, in get_profile
    raise MacsypyError(f"'{model_location.name}/{gene.name}': No such profile")
macsypy.error.MacsypyError: 'defense-finder-models/Rst_Hydrolase-Tm__Hydrolase-Tm': No such profile

```

**Comment by chrisdoering8197** [comment]
I apologize I commented on the wrong repo there is a similar thread here: https://github.com/mdmparis/defense-finder/issues/42
